#!/usr/bin/env python3
"""
setup_env.py

Interactive setup script to help users configure their .env file.
"""
import os
import sys
from pathlib import Path

def main():
    """Interactive setup for .env configuration."""
    print("🔧 GotLockz Bot Environment Setup")
    print("=" * 40)
    
    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    print("\n📝 Please provide the following information:")
    print("(Press Enter to skip optional fields)\n")
    
    # Collect configuration
    config = {}
    
    # Required fields
    config['DISCORD_TOKEN'] = input("Discord Bot Token (required): ").strip()
    if not config['DISCORD_TOKEN']:
        print("❌ Discord token is required!")
        return
    
    config['GUILD_ID'] = input("Discord Server (Guild) ID (required): ").strip()
    if not config['GUILD_ID']:
        print("❌ Guild ID is required!")
        return
    
    config['OPENAI_API_KEY'] = input("OpenAI API Key (required): ").strip()
    if not config['OPENAI_API_KEY']:
        print("❌ OpenAI API key is required!")
        return
    
    # Channel IDs
    print("\n📺 Channel IDs (required):")
    config['ANALYSIS_CHANNEL_ID'] = input("Analysis Channel ID: ").strip()
    config['VIP_CHANNEL_ID'] = input("VIP Picks Channel ID: ").strip()
    config['LOTTO_CHANNEL_ID'] = input("Lotto Picks Channel ID: ").strip()
    config['FREE_CHANNEL_ID'] = input("Free Picks Channel ID: ").strip()
    
    # Optional fields
    print("\n⚙️  Optional Configuration:")
    config['OWNER_ID'] = input("Bot Owner Discord User ID (optional): ").strip()
    
    # AI Configuration
    config['OPENAI_MODEL'] = input("OpenAI Model (default: gpt-4): ").strip() or "gpt-4"
    config['ANALYSIS_TEMPERATURE'] = input("Analysis Temperature (default: 0.7): ").strip() or "0.7"
    
    # File paths
    config['COUNTER_FILE'] = input("Counter File Path (default: counters.json): ").strip() or "counters.json"
    config['LOG_FILE'] = input("Log File Path (default: gotlockz-bot.log): ").strip() or "gotlockz-bot.log"
    
    # Google Sheets (optional)
    config['GOOGLE_CREDENTIALS_PATH'] = input("Google Credentials Path (optional): ").strip()
    config['GOOGLE_SHEET_NAME'] = input("Google Sheet Name (default: GotLockz Picks): ").strip() or "GotLockz Picks"
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write("# GotLockz Bot Environment Configuration\n")
            f.write("# Generated by setup_env.py\n\n")
            
            for key, value in config.items():
                if value:  # Only write non-empty values
                    f.write(f"{key}={value}\n")
        
        print("\n✅ .env file created successfully!")
        print("\n📋 Next steps:")
        print("1. Review your .env file")
        print("2. Install dependencies: pip install -r requirements.txt")
        print("3. Run the bot: python main.py")
        print("\n🔒 Security reminder: Never commit your .env file to version control!")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return

if __name__ == "__main__":
    main()
